### ISSUE TITLE
Hey, is it current? Thanks for the pdf though!

### ISSUE THREAD

**Issue by AnonymoZ** [Dhanton/quantum-chess#1]
MAX_QUBIT_MEMORY = backend.MAX_QUBIT_MEMORY
AttributeError: 'QasmSimulator' object has no attribute 'MAX_QUBIT_MEMORY'

**Comment by dhanton** [comment]
Hey so yeah this is a pretty old project, I'm not maintaining it anymore, sorry. But thanks for your interest! Feel free to add a PR if you can fix this and I'll approve it. The issue is probably related to an old version of Qiskit.
